name: demo

plugins:
  - name: solidity
    version: 0.7.0

dependencies:
  - name: solmate
    github: transmissions11/solmate
    ref: "v6"
    contracts_folder: src
    config_override:
      compile:
        exclude: 
          - ./test/utils/*


solidity:
  version: 0.8.23
  import_remapping:
    - "@solmate=solmate/v6"
